AWSTemplateFormatVersion: 2010-09-09
Description: |
  Kittens Carousel is a static website application deployed with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.
# Use public Systems Manager Parameter
Parameters:
  LatestAmiId:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64" # Latest, up-to-date and free 'ami'

Resources:
  myucelinstanceWS:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId # we give ami reference
      InstanceType: t2.micro
      KeyName: firstkey # Use your own key pair without ".pem"
      SecurityGroups:
        - !Ref myucelinstanceSG
      Tags:
        - Key: Name
          Value: myucel-kittens-carousel-project
      UserData:
        Fn::Base64: |
          #! /bin/bash
          sudo yum update -y 
          sudo yum install httpd -y
          cd /var/www/html
          sudo chmod -R 777 /var/www/html
          sudo rm index.html
          FOLDER="https://raw.githubusercontent.com/myucel92/101-kittens-carousel-static-website-ec2/main/static-web"
          sudo wget $FOLDER/index.html
          sudo wget $FOLDER/cat0.jpg
          sudo wget $FOLDER/cat1.jpg
          sudo wget $FOLDER/cat2.jpg
          sudo wget $FOLDER/clarusway-logo-classic.jpg
          sudo systemctl start httpd
          sudo systemctl enable httpd

  myucelinstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH - Http # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
